/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ccm_auto_insert;

import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author oholik
 */
public class MenuGUI_jFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MenuGUI_jFrame() {
        initComponents();
//        this.MobilCZ_VSE_button.setVisible(false);
//        this.MobilCZ_Postpaid_button.setVisible(false);

    }

//    public static void main(String[] args) {
//        NewJFrame myFrame = new NewJFrame();
//        myFrame.setVisible(true);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mojeGroupa = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton_Tel_linka_Postpaid_NGOSIP = new javax.swing.JButton();
        jButton_Tel_linka_Postpaid_Trifid = new javax.swing.JButton();
        GSM_Postpaid_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton_Tel_linka_Postpaid_Trifid_nova_faktura = new javax.swing.JButton();
        jButton_Tel_linka_VSE_Trifid_Pridruzeni = new javax.swing.JButton();
        jButton_Tel_linka_VSE_Trifid_nova_faktura = new javax.swing.JButton();
        jButton_Tel_linka_Postpaid_Trifid_Pridruzeni = new javax.swing.JButton();
        GSM_Postpaid_pridruzeni_button = new javax.swing.JButton();
        GSM_VSE_pridruzeni_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        GSM_VSE_nova_faktura = new javax.swing.JButton();
        GSM_aktivace_potenciala = new javax.swing.JButton();
        GSM_LE_s_BA = new javax.swing.JButton();
        GSM_LE_bez_BA = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        GSM_VSE_button = new javax.swing.JButton();
        jButton_VSE_Autopark = new javax.swing.JButton();
        jButton_Tel_linka_VSE_NGOSIP = new javax.swing.JButton();
        jButton_Tel_linka_VSE = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        DSLMulti_VSE_button = new javax.swing.JButton();
        telefonni_linka_vse_ngosip_asc = new javax.swing.JButton();
        VSE_voip = new javax.swing.JButton();
        DSLSimple_VSE_button = new javax.swing.JButton();
        jButton_GSM_VSE_Shop = new javax.swing.JButton();
        jButtonTCloud = new javax.swing.JButton();
        DSL_reselling_VSE_button = new javax.swing.JButton();
        jRadioButton_test1 = new javax.swing.JRadioButton();
        jRadioButton_test2 = new javax.swing.JRadioButton();
        jTextFieldCisloKPridruzeni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Lessana_GSM_postpaid = new javax.swing.JButton();
        cuid_predseda = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pocetZakazniku = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jButton_CCM_dokonceni_zadosti = new javax.swing.JButton();
        jTextField3_pocetZakazniku = new javax.swing.JTextField();
        jCheckBox1_dokoncit = new javax.swing.JCheckBox();
        jButton4_CLF_check = new javax.swing.JButton();
        jButton5_ODS_check = new javax.swing.JButton();
        jCheckBox1_splatkac = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextField_ICO = new javax.swing.JTextField();
        jRadioButton_test3 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox1_ICOzeSouboru = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        MobilCZ_VSE_button = new javax.swing.JButton();
        MobilCZ_Postpaid_button = new javax.swing.JButton();
        jRadioButton1_tarif = new javax.swing.JRadioButton();
        jRadioButton2_tarif = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Mobilcz_pridruzeni = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        RWE_VSE_button1 = new javax.swing.JButton();
        RWE_Postpaid_button1 = new javax.swing.JButton();
        jButtonRWE_PridruzeniSU = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ViceSU = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonKonec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jButton_Tel_linka_Postpaid_NGOSIP.setText("Telefonní linka - Postpaid - NGOSIP");
        jButton_Tel_linka_Postpaid_NGOSIP.setEnabled(false);
        jButton_Tel_linka_Postpaid_NGOSIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Tel_linka_Postpaid_NGOSIPActionPerformed(evt);
            }
        });

        jButton_Tel_linka_Postpaid_Trifid.setText("Telefonní linka - Postpaid - Trifid");
        jButton_Tel_linka_Postpaid_Trifid.setEnabled(false);
        jButton_Tel_linka_Postpaid_Trifid.setPreferredSize(new java.awt.Dimension(233, 25));
        jButton_Tel_linka_Postpaid_Trifid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Tel_linka_Postpaid_TrifidActionPerformed(evt);
            }
        });

        GSM_Postpaid_button.setText("GSM Postpaid");
        GSM_Postpaid_button.setCursor(new java.awt.Cursor(java.awt.Cursor.SW_RESIZE_CURSOR));
        GSM_Postpaid_button.setEnabled(false);
        GSM_Postpaid_button.setMaximumSize(new java.awt.Dimension(233, 25));
        GSM_Postpaid_button.setMinimumSize(new java.awt.Dimension(233, 25));
        GSM_Postpaid_button.setPreferredSize(new java.awt.Dimension(233, 25));
        GSM_Postpaid_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GSM_Postpaid_buttonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PostPaid - RČ - nový zákazník");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Tel_linka_Postpaid_Trifid, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(jButton_Tel_linka_Postpaid_NGOSIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GSM_Postpaid_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(GSM_Postpaid_button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Tel_linka_Postpaid_NGOSIP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Tel_linka_Postpaid_Trifid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel3.setBackground(new java.awt.Color(0, 255, 51));

        jButton_Tel_linka_Postpaid_Trifid_nova_faktura.setText("Telefonní linka - Postpaid - Trifid - Nová faktura");
        jButton_Tel_linka_Postpaid_Trifid_nova_faktura.setMaximumSize(new java.awt.Dimension(265, 25));
        jButton_Tel_linka_Postpaid_Trifid_nova_faktura.setMinimumSize(new java.awt.Dimension(265, 25));
        jButton_Tel_linka_Postpaid_Trifid_nova_faktura.setPreferredSize(new java.awt.Dimension(265, 25));
        jButton_Tel_linka_Postpaid_Trifid_nova_faktura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Tel_linka_Postpaid_Trifid_nova_fakturaActionPerformed(evt);
            }
        });

        jButton_Tel_linka_VSE_Trifid_Pridruzeni.setText("Telefonní linka - VSE - Trifid - Přidružení");
        jButton_Tel_linka_VSE_Trifid_Pridruzeni.setPreferredSize(new java.awt.Dimension(350, 25));
        jButton_Tel_linka_VSE_Trifid_Pridruzeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Tel_linka_VSE_Trifid_PridruzeniActionPerformed(evt);
            }
        });

        jButton_Tel_linka_VSE_Trifid_nova_faktura.setText("Telefonní linka - VSE - Trifid - Nová faktura");
        jButton_Tel_linka_VSE_Trifid_nova_faktura.setMaximumSize(new java.awt.Dimension(265, 25));
        jButton_Tel_linka_VSE_Trifid_nova_faktura.setMinimumSize(new java.awt.Dimension(265, 25));
        jButton_Tel_linka_VSE_Trifid_nova_faktura.setPreferredSize(new java.awt.Dimension(265, 25));
        jButton_Tel_linka_VSE_Trifid_nova_faktura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Tel_linka_VSE_Trifid_nova_fakturaActionPerformed(evt);
            }
        });

        jButton_Tel_linka_Postpaid_Trifid_Pridruzeni.setText("Telefonní linka - Postpaid - Trifid - Přidružení");
        jButton_Tel_linka_Postpaid_Trifid_Pridruzeni.setMaximumSize(new java.awt.Dimension(265, 25));
        jButton_Tel_linka_Postpaid_Trifid_Pridruzeni.setMinimumSize(new java.awt.Dimension(265, 25));
        jButton_Tel_linka_Postpaid_Trifid_Pridruzeni.setPreferredSize(new java.awt.Dimension(265, 25));
        jButton_Tel_linka_Postpaid_Trifid_Pridruzeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Tel_linka_Postpaid_Trifid_PridruzeniActionPerformed(evt);
            }
        });

        GSM_Postpaid_pridruzeni_button.setText("GSM Postpaid Přidružení");
        GSM_Postpaid_pridruzeni_button.setMaximumSize(new java.awt.Dimension(265, 25));
        GSM_Postpaid_pridruzeni_button.setMinimumSize(new java.awt.Dimension(265, 25));
        GSM_Postpaid_pridruzeni_button.setPreferredSize(new java.awt.Dimension(265, 25));
        GSM_Postpaid_pridruzeni_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GSM_Postpaid_pridruzeni_buttonActionPerformed(evt);
            }
        });

        GSM_VSE_pridruzeni_button.setText("GSM VSE Přidružení");
        GSM_VSE_pridruzeni_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GSM_VSE_pridruzeni_buttonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Přidružení a nové faktury");

        GSM_VSE_nova_faktura.setText("GSM VSE Nova faktura");
        GSM_VSE_nova_faktura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GSM_VSE_nova_fakturaActionPerformed(evt);
            }
        });

        GSM_aktivace_potenciala.setText("GSM aktivaci potenciála z ngCRM");
        GSM_aktivace_potenciala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GSM_aktivace_potencialaActionPerformed(evt);
            }
        });

        GSM_LE_s_BA.setText("GSM LE Přidružení do BA");
        GSM_LE_s_BA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GSM_LE_s_BAActionPerformed(evt);
            }
        });

        GSM_LE_bez_BA.setText("GSM LE Přidružení bez BA");
        GSM_LE_bez_BA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GSM_LE_bez_BAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(GSM_VSE_nova_faktura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Tel_linka_VSE_Trifid_Pridruzeni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Tel_linka_VSE_Trifid_nova_faktura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Tel_linka_Postpaid_Trifid_Pridruzeni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Tel_linka_Postpaid_Trifid_nova_faktura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GSM_Postpaid_pridruzeni_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GSM_VSE_pridruzeni_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GSM_aktivace_potenciala, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GSM_LE_s_BA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GSM_LE_bez_BA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Tel_linka_VSE_Trifid_Pridruzeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Tel_linka_VSE_Trifid_nova_faktura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Tel_linka_Postpaid_Trifid_nova_faktura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Tel_linka_Postpaid_Trifid_Pridruzeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GSM_Postpaid_pridruzeni_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GSM_VSE_pridruzeni_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GSM_VSE_nova_faktura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GSM_aktivace_potenciala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GSM_LE_s_BA)
                .addGap(18, 18, 18)
                .addComponent(GSM_LE_bez_BA)
                .addGap(170, 170, 170))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 51));

        GSM_VSE_button.setText("GSM VSE");
        GSM_VSE_button.setMaximumSize(new java.awt.Dimension(195, 25));
        GSM_VSE_button.setMinimumSize(new java.awt.Dimension(195, 25));
        GSM_VSE_button.setPreferredSize(new java.awt.Dimension(195, 25));
        GSM_VSE_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GSM_VSE_buttonActionPerformed(evt);
            }
        });

        jButton_VSE_Autopark.setText("Autopark_NGOSIP");
        jButton_VSE_Autopark.setMaximumSize(new java.awt.Dimension(195, 25));
        jButton_VSE_Autopark.setMinimumSize(new java.awt.Dimension(195, 25));
        jButton_VSE_Autopark.setPreferredSize(new java.awt.Dimension(195, 25));
        jButton_VSE_Autopark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VSE_AutoparkActionPerformed(evt);
            }
        });

        jButton_Tel_linka_VSE_NGOSIP.setText("Telefonní linka - VSE - NGOSIP");
        jButton_Tel_linka_VSE_NGOSIP.setMaximumSize(new java.awt.Dimension(195, 25));
        jButton_Tel_linka_VSE_NGOSIP.setMinimumSize(new java.awt.Dimension(195, 25));
        jButton_Tel_linka_VSE_NGOSIP.setPreferredSize(new java.awt.Dimension(195, 25));
        jButton_Tel_linka_VSE_NGOSIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Tel_linka_VSE_NGOSIPActionPerformed(evt);
            }
        });

        jButton_Tel_linka_VSE.setText("Telefonní linka - VSE - Trifid");
        jButton_Tel_linka_VSE.setPreferredSize(new java.awt.Dimension(230, 25));
        jButton_Tel_linka_VSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Tel_linka_VSEActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VSE - nový zakazník");

        DSLMulti_VSE_button.setText("DSL Multi");
        DSLMulti_VSE_button.setToolTipText("");
        DSLMulti_VSE_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSLMulti_VSE_buttonActionPerformed(evt);
            }
        });

        telefonni_linka_vse_ngosip_asc.setText("Telefonní linka - VSE - NGOSIP - ASC");
        telefonni_linka_vse_ngosip_asc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonni_linka_vse_ngosip_ascActionPerformed(evt);
            }
        });

        VSE_voip.setText("VSE - Voip");
        VSE_voip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VSE_voipActionPerformed(evt);
            }
        });

        DSLSimple_VSE_button.setText("DSL Simple");
        DSLSimple_VSE_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSLSimple_VSE_buttonActionPerformed(evt);
            }
        });

        jButton_GSM_VSE_Shop.setText("GSM VSE - shop");
        jButton_GSM_VSE_Shop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GSM_VSE_ShopActionPerformed(evt);
            }
        });

        jButtonTCloud.setText("T-Cloud");
        jButtonTCloud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTCloudActionPerformed(evt);
            }
        });

        DSL_reselling_VSE_button.setText("DSL Reselling");
        DSL_reselling_VSE_button.setToolTipText("");
        DSL_reselling_VSE_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSL_reselling_VSE_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DSL_reselling_VSE_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VSE_voip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DSLMulti_VSE_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton_Tel_linka_VSE_NGOSIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_VSE_Autopark, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GSM_VSE_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_Tel_linka_VSE, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(telefonni_linka_vse_ngosip_asc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(DSLSimple_VSE_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_GSM_VSE_Shop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTCloud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton_Tel_linka_VSE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Tel_linka_VSE_NGOSIP, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_VSE_Autopark, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GSM_VSE_button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DSLMulti_VSE_button)
                .addGap(6, 6, 6)
                .addComponent(DSLSimple_VSE_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonni_linka_vse_ngosip_asc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VSE_voip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_GSM_VSE_Shop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonTCloud)
                .addGap(18, 18, 18)
                .addComponent(DSL_reselling_VSE_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mojeGroupa.add(jRadioButton_test1);
        jRadioButton_test1.setText("test1");

        mojeGroupa.add(jRadioButton_test2);
        jRadioButton_test2.setSelected(true);
        jRadioButton_test2.setText("test2");

        jLabel2.setText("Vložte tel. číslo");

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Lessana");

        Lessana_GSM_postpaid.setText("Nový zákazník - GSM postpaid");
        Lessana_GSM_postpaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lessana_GSM_postpaidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lessana_GSM_postpaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lessana_GSM_postpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        jLabel11.setText("Počet zákazníků:");

        pocetZakazniku.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel12.setText("Vytvořeno Zákazníků");

        jButton_CCM_dokonceni_zadosti.setText("CCM - dokončení žádosti");
        jButton_CCM_dokonceni_zadosti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CCM_dokonceni_zadostiActionPerformed(evt);
            }
        });

        jTextField3_pocetZakazniku.setEditable(false);
        jTextField3_pocetZakazniku.setText("0");

        jCheckBox1_dokoncit.setText("Automaticky dokončit");

        jButton4_CLF_check.setText("Kontrola CLF");
        jButton4_CLF_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_CLF_checkActionPerformed(evt);
            }
        });

        jButton5_ODS_check.setText("Kontrola ODS");
        jButton5_ODS_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_ODS_checkActionPerformed(evt);
            }
        });

        jCheckBox1_splatkac.setText("Splátkový kalendář");

        jLabel1.setText("vložte IČO");

        mojeGroupa.add(jRadioButton_test3);
        jRadioButton_test3.setText("test3");

        jLabel10.setText("Předseda Lessany - CUID");

        jCheckBox1_ICOzeSouboru.setText("ICO ze souboru(platí pro GSM VSE)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_CCM_dokonceni_zadosti, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4_CLF_check, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5_ODS_check, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1_splatkac)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(140, 140, 140)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pocetZakazniku, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField3_pocetZakazniku, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox1_dokoncit, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton_test1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jRadioButton_test2, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jRadioButton_test3))))
                        .addGap(18, 18, 18))
                    .addComponent(jCheckBox1_ICOzeSouboru))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldCisloKPridruzeni, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(jTextField_ICO))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cuid_predseda, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCisloKPridruzeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(cuid_predseda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_ICO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pocetZakazniku))
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField3_pocetZakazniku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRadioButton_test2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jCheckBox1_dokoncit)
                                            .addComponent(jRadioButton_test3)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton_test1)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addComponent(jCheckBox1_splatkac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox1_ICOzeSouboru)
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_CCM_dokonceni_zadosti)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4_CLF_check)
                                .addGap(3, 3, 3)
                                .addComponent(jButton5_ODS_check, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        jTextField3_pocetZakazniku.getAccessibleContext().setAccessibleName("");
        jTextField3_pocetZakazniku.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("TMCZ", jPanel1);

        MobilCZ_VSE_button.setText("MobilCZ VSE");
        MobilCZ_VSE_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobilCZ_VSE_buttonActionPerformed(evt);
            }
        });

        MobilCZ_Postpaid_button.setText("MobilCZ Postpaid");
        MobilCZ_Postpaid_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobilCZ_Postpaid_buttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1_tarif);
        jRadioButton1_tarif.setSelected(true);
        jRadioButton1_tarif.setText("Tarif - standart");

        buttonGroup1.add(jRadioButton2_tarif);
        jRadioButton2_tarif.setText("Tarif - bez limitu");

        jLabel6.setText("Vložte RČ");

        Mobilcz_pridruzeni.setText("MobilCZ - Přidružení SU");
        Mobilcz_pridruzeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mobilcz_pridruzeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MobilCZ_Postpaid_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MobilCZ_VSE_button, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1_tarif)
                    .addComponent(jRadioButton2_tarif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Mobilcz_pridruzeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(365, 365, 365))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jRadioButton1_tarif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2_tarif))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(Mobilcz_pridruzeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(MobilCZ_VSE_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(MobilCZ_Postpaid_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(415, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mobilcz", jPanel4);

        RWE_VSE_button1.setText("RWE VSE");
        RWE_VSE_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RWE_VSE_button1ActionPerformed(evt);
            }
        });

        RWE_Postpaid_button1.setText("RWE Postpaid");
        RWE_Postpaid_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RWE_Postpaid_button1ActionPerformed(evt);
            }
        });

        jButtonRWE_PridruzeniSU.setText("RWE přidružení SU");
        jButtonRWE_PridruzeniSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRWE_PridruzeniSUActionPerformed(evt);
            }
        });

        jLabel7.setText("Vložte RČ");

        jLabel8.setText("Počet SU pod CU");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonRWE_PridruzeniSU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RWE_Postpaid_button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RWE_VSE_button1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(ViceSU))
                .addContainerGap(845, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RWE_VSE_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RWE_Postpaid_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ViceSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRWE_PridruzeniSU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("RWE", jPanel6);

        jButtonKonec.setText("Konec");
        jButtonKonec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKonecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(405, 405, 405)
                .addComponent(jButtonKonec, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonKonec, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKonecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKonecActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonKonecActionPerformed

    public int funkceHodnotaButtonu_Prostredi() {
        int hodnota = 0;
        if (jRadioButton_test1.isSelected() == true) {
            hodnota = 1;
        } else if (jRadioButton_test2.isSelected() == true) {
            hodnota = 2;
        } else if (jRadioButton_test3.isSelected() == true) {
            hodnota = 3;
        }
        return hodnota;
    }

    public String mobilcz_tarif() {
        String retezec = "MOBIL.CZ STANDARD";
        if (jRadioButton1_tarif.isSelected() == true) {
            retezec = "MOBIL.CZ STANDARD";
        } else {
            retezec = "MOBIL.CZ BEZ LIMITU";
        }
        return retezec;
    }


    private void jButton_Tel_linka_VSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Tel_linka_VSEActionPerformed

        int prostredi = funkceHodnotaButtonu_Prostredi();
//        String ICOString = jTextField_ICO.getText();
//        if (jTextField_ICO.getText().equals("")) {
//            Component frame = null;
//            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň hodnotu IČO");
//        } else {
//            int ICOInt = Integer.parseInt(ICOString);
        try {
            TelLinka_VSE_Trifid.proved_TelLinka_VSE_skript(prostredi);
        } catch (InterruptedException | SQLException ex) {
            Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton_Tel_linka_VSEActionPerformed


    private void jButton_Tel_linka_Postpaid_NGOSIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Tel_linka_Postpaid_NGOSIPActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
        TelLinka_Postpaid_NGOSIP.proved_TelLinka_Postpaid_NGOSIP_skript(prostredi);

    }//GEN-LAST:event_jButton_Tel_linka_Postpaid_NGOSIPActionPerformed

    private void jButton_Tel_linka_VSE_NGOSIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Tel_linka_VSE_NGOSIPActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
//        String ICOString = jTextField_ICO.getText();
//        if (jTextField_ICO.getText().equals("")) {
//            Component frame = null;
//            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň hodnotu IČO");
//        } else {
//            int ICOInt = Integer.parseInt(ICOString);
//
//            TelLinka_VSE_NGOSIP provedAkci = new TelLinka_VSE_NGOSIP();
        try {
            TelLinka_VSE_NGOSIP.telLinka(prostredi);
        } catch (SQLException ex) {
            Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);

    }//GEN-LAST:event_jButton_Tel_linka_VSE_NGOSIPActionPerformed
    }
    private void jButton_Tel_linka_Postpaid_TrifidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Tel_linka_Postpaid_TrifidActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
        TelLinka_Postpaid_Trifid.proved_TelLinka_Postpaid_Trifid_skript(prostredi);
    }//GEN-LAST:event_jButton_Tel_linka_Postpaid_TrifidActionPerformed

    private void jButton_VSE_AutoparkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VSE_AutoparkActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
        //String ICOString = jTextField_ICO.getText();
        boolean splatkac = jCheckBox1_splatkac.isSelected();
//        if (jTextField_ICO.getText().equals("")) {
//            Component frame = null;
//            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň hodnotu IČO");
//        } else {
//            int ICOInt = Integer.parseInt(ICOString);

        //Autopark_VSE_NGOSIP provedAkci = new Autopark_VSE_NGOSIP();
        try {
            Autopark_VSE_NGOSIP.proved_Autopark_VSE_skript(prostredi, splatkac);
        } catch (SQLException ex) {
            Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_VSE_AutoparkActionPerformed

    private void jButton_Tel_linka_VSE_Trifid_PridruzeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Tel_linka_VSE_Trifid_PridruzeniActionPerformed

        int prostredi = funkceHodnotaButtonu_Prostredi();
        String telCisloProPridruzeniString = jTextFieldCisloKPridruzeni.getText();
        if (jTextFieldCisloKPridruzeni.getText().equals("")) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň telefonní čislo k přiřazení");
        } else {
            int telCisloProPridruzeniInt = Integer.parseInt(telCisloProPridruzeniString);
            TelLinka_VSE_Trifid_Pridruzeni.proved_TelLinka_VSE_Trifid_Pridruzeni_skript(telCisloProPridruzeniInt, prostredi);
        }
    }//GEN-LAST:event_jButton_Tel_linka_VSE_Trifid_PridruzeniActionPerformed

    private void jButton_Tel_linka_Postpaid_Trifid_PridruzeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Tel_linka_Postpaid_Trifid_PridruzeniActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
        String telCisloProPridruzeniString = jTextFieldCisloKPridruzeni.getText();
        if (jTextFieldCisloKPridruzeni.getText().equals("")) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň telefonní čislo k přiřazení");
        } else {
            int telCisloProPridruzeniInt = Integer.parseInt(telCisloProPridruzeniString);
            TelLinka_Postpaid_Trifid_Pridruzeni.proved_TelLinka_Postpaid_Trifid_Pridruzeni_skript(telCisloProPridruzeniInt, prostredi);
    }//GEN-LAST:event_jButton_Tel_linka_Postpaid_Trifid_PridruzeniActionPerformed
    }
    private void jButton_Tel_linka_VSE_Trifid_nova_fakturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Tel_linka_VSE_Trifid_nova_fakturaActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
        String telCisloProPridruzeniString = jTextFieldCisloKPridruzeni.getText();
        if (jTextFieldCisloKPridruzeni.getText().equals("")) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň telefonní čislo k přiřazení");
        } else {
            int telCisloProPridruzeniInt = Integer.parseInt(telCisloProPridruzeniString);
            TelLinka_VSE_Trifid_NovaFaktura.proved_TelLinka_VSE_Trifid_NovaFaktura_skript(telCisloProPridruzeniInt, prostredi);
    }//GEN-LAST:event_jButton_Tel_linka_VSE_Trifid_nova_fakturaActionPerformed
    }
    private void jButton_Tel_linka_Postpaid_Trifid_nova_fakturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Tel_linka_Postpaid_Trifid_nova_fakturaActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
        String telCisloProPridruzeniString = jTextFieldCisloKPridruzeni.getText();
        if (jTextFieldCisloKPridruzeni.getText().equals("")) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň telefonní čislo k přiřazení");
        } else {
            int telCisloProPridruzeniInt = Integer.parseInt(telCisloProPridruzeniString);
            TelLinka_Postpaid_Trifid_NovaFaktura.proved_TelLinka_Postpaid_Trifid_NovaFaktura_skript(telCisloProPridruzeniInt, prostredi);
    }//GEN-LAST:event_jButton_Tel_linka_Postpaid_Trifid_nova_fakturaActionPerformed
    }

    private void GSM_VSE_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GSM_VSE_buttonActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
        int Zakaznici_pocet = (int) pocetZakazniku.getValue();
        boolean dokoncit = jCheckBox1_dokoncit.isSelected();
        boolean ICO_ze_souboru = jCheckBox1_ICOzeSouboru.isSelected();
//            String ICOString = jTextField_ICO.getText();
//         if (jTextField_ICO.getText().equals("")) {
//         Component frame = null;
//         JOptionPane.showMessageDialog(frame, "Nejdříve vyplň hodnotu IČO");
//         } else {
//         int ICOInt = Integer.parseInt(ICOString);

        try {
            GSM_VSE.proved_GSM_VSE_skript(prostredi, Zakaznici_pocet, dokoncit, jTextField3_pocetZakazniku, ICO_ze_souboru);
        } catch (SQLException ex) {
            Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GSM_VSE_buttonActionPerformed

    private void GSM_Postpaid_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GSM_Postpaid_buttonActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
        GSM_Postpaid.proved_GSM_Postpaid_skript(prostredi);
    }//GEN-LAST:event_GSM_Postpaid_buttonActionPerformed

    private void GSM_VSE_pridruzeni_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GSM_VSE_pridruzeni_buttonActionPerformed

        int prostredi = funkceHodnotaButtonu_Prostredi();
        String telCisloProPridruzeniString = jTextFieldCisloKPridruzeni.getText();
        if (jTextFieldCisloKPridruzeni.getText().equals("")) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň telefonní čislo k přiřazení");
        } else {
            int telCisloProPridruzeniInt = Integer.parseInt(telCisloProPridruzeniString);
            try {
                GSM_VSE_Pridruzeni.proved_GSM_VSE_Pridruzeni_skript(telCisloProPridruzeniInt, prostredi);
            } catch (SQLException ex) {
                Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_GSM_VSE_pridruzeni_buttonActionPerformed

    private void GSM_Postpaid_pridruzeni_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GSM_Postpaid_pridruzeni_buttonActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
        String telCisloProPridruzeniString = jTextFieldCisloKPridruzeni.getText();
        if (jTextFieldCisloKPridruzeni.getText().equals("")) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň telefonní čislo k přiřazení");
        } else {
            int telCisloProPridruzeniInt = Integer.parseInt(telCisloProPridruzeniString);
            GSM_Postpaid_Pridruzeni.proved_GSM_Postpaid_Pridruzeni_skript(telCisloProPridruzeniInt, prostredi);
        }
    }//GEN-LAST:event_GSM_Postpaid_pridruzeni_buttonActionPerformed

    private void MobilCZ_Postpaid_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobilCZ_Postpaid_buttonActionPerformed
        String prostredi = mobilcz_tarif();
        MobilCZ_Postpaid_aktivace.proved_MobilCZ_Postpaid_aktivace_skript(prostredi);
    }//GEN-LAST:event_MobilCZ_Postpaid_buttonActionPerformed

    private void MobilCZ_VSE_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobilCZ_VSE_buttonActionPerformed
        String prostredi = mobilcz_tarif();
//        String ICOString = jTextField_ICO.getText();
//        if (jTextField_ICO.getText().equals("")) {
//            Component frame = null;
//            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň hodnotu IČO");
//        } else {
//            int ICOInt = Integer.parseInt(ICOString);

        try {
            MobilCZ_VSE_aktivace.proved_MobilCZ_VSE_aktivace_skript(prostredi);
        } catch (SQLException ex) {
            Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
//        }
    }//GEN-LAST:event_MobilCZ_VSE_buttonActionPerformed

    private void RWE_VSE_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RWE_VSE_button1ActionPerformed
        try {
            //int hodnotaButtonu = funkceHodnotaButtonu();
//        String ICOString = jTextField_ICO.getText();
//        if (jTextField_ICO.getText().equals("")) {
//            Component frame = null;
//            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň hodnotu IČO");
//        } else {
//            int ICOInt = Integer.parseInt(ICOString);

            RWE_VSE_aktivace.proved_RWE_VSE_aktivace_skript(/*ICOInt, hodnotaButtonu*/);
//        }
        } catch (SQLException ex) {
            Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RWE_VSE_button1ActionPerformed

    private void RWE_Postpaid_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RWE_Postpaid_button1ActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
        RWE_Postpaid_aktivace.proved_RWE_Postpaid_aktivace_skript(prostredi, Integer.parseInt(ViceSU.getText()));
    }//GEN-LAST:event_RWE_Postpaid_button1ActionPerformed

    private void Mobilcz_pridruzeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mobilcz_pridruzeniActionPerformed
        String rc = jTextField2.getText();
        if (jTextField2.getText().equals("")) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň hodnotu rodné číslo");
        } else {
            MobilCZ_pridruzeni.proved_MobilCZ_pridruzeni_skript(rc, mobilcz_tarif());
        }

    }//GEN-LAST:event_Mobilcz_pridruzeniActionPerformed

    private void jButtonRWE_PridruzeniSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRWE_PridruzeniSUActionPerformed
        String rc = jTextField1.getText();
        if (jTextField1.getText().equals("")) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň hodnotu rodné číslo");
        } else {
            RWE_pridruzeni.proved_RWE_pridruzeni_skript(rc);
        }
    }//GEN-LAST:event_jButtonRWE_PridruzeniSUActionPerformed

    private void DSLMulti_VSE_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DSLMulti_VSE_buttonActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
        String ICOString = jTextField_ICO.getText();
        if (jTextField_ICO.getText().equals("")) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň hodnotu IČO");
        } else {

            try {
                xDSL_VSE.proved_xDSL_VSE_skript(ICOString, prostredi);

            } catch (InterruptedException ex) {
                Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_DSLMulti_VSE_buttonActionPerformed

    private void telefonni_linka_vse_ngosip_ascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonni_linka_vse_ngosip_ascActionPerformed

        int prostredi = funkceHodnotaButtonu_Prostredi();
//        String ICOString = jTextField_ICO.getText();
//        if (jTextField_ICO.getText().equals("")) {
//            Component frame = null;
//            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň hodnotu IČO");
//        } else {
//            int ICOInt = Integer.parseInt(ICOString);

        try {
            TelLinka_VSE_NGOSIP_ASC.proved_TelLinka_VSE_NGOSIP_ASC_skript(prostredi);
        } catch (SQLException ex) {
            Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_telefonni_linka_vse_ngosip_ascActionPerformed


    private void VSE_voipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VSE_voipActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
        int Zakaznici_pocet = (int) pocetZakazniku.getValue();
        boolean dokoncit = jCheckBox1_dokoncit.isSelected();

        try {
            TelLinka_VSE_Voip.proved_TelLinka_VSE_Voip_skript(prostredi, Zakaznici_pocet, dokoncit);
        } catch (SQLException ex) {
            Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_VSE_voipActionPerformed

    private void Lessana_GSM_postpaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lessana_GSM_postpaidActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();

        String predseda = cuid_predseda.getText();
        if (cuid_predseda.getText().equals("")) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Zadejte CUID zakaznika s předsedou");
        } else {
            GSM_Postpaid_lessana.proved_GSM_Postpaid_lessana_skript(prostredi, predseda);
        }
    }//GEN-LAST:event_Lessana_GSM_postpaidActionPerformed

    private void GSM_VSE_nova_fakturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GSM_VSE_nova_fakturaActionPerformed

        int prostredi = funkceHodnotaButtonu_Prostredi();
        String telCisloProPridruzeniString = jTextFieldCisloKPridruzeni.getText();
        if (jTextFieldCisloKPridruzeni.getText().equals("")) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň telefonní čislo k přiřazení");
        } else {
            int telCisloProPridruzeniInt = Integer.parseInt(telCisloProPridruzeniString);
            GSM_VSE_Nova_faktura.proved_GSM_VSE_Nova_faktura_skript(telCisloProPridruzeniInt, prostredi);
        }
    }//GEN-LAST:event_GSM_VSE_nova_fakturaActionPerformed

    private void DSLSimple_VSE_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DSLSimple_VSE_buttonActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
        String ICOString = jTextField_ICO.getText();
        if (jTextField_ICO.getText().equals("")) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň hodnotu IČO");
        } else {
            try {
                DSL_SIMPLE_VSE_SME.proved_DSL_SIMPLE_VSE_SME_skript(ICOString, prostredi);

                //xDSL_VSE.telLinka(ICOInt, hodnotaButtonu);
            } catch (InterruptedException ex) {
                Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }  // TODO add your handling code here:
    }//GEN-LAST:event_DSLSimple_VSE_buttonActionPerformed

    private void jButton_CCM_dokonceni_zadostiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CCM_dokonceni_zadostiActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
        int Zakaznici_pocet = (int) pocetZakazniku.getValue();

        try {
            CCMDokonceni.dokonceni(prostredi, Zakaznici_pocet);
        } catch (SQLException ex) {
            Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_CCM_dokonceni_zadostiActionPerformed

    private void jButton4_CLF_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_CLF_checkActionPerformed
        //CHECK_MSISDN_IN_CLF check = new CHECK_MSISDN_IN_CLF(prostredi);

        int prostredi = funkceHodnotaButtonu_Prostredi();
        CHECK_MSISDN_IN_CLF.spustCheckCLF(prostredi);

    }//GEN-LAST:event_jButton4_CLF_checkActionPerformed

    private void jButton5_ODS_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_ODS_checkActionPerformed
//        CHECK_MSISDN_IN_ODS check = new CHECK_MSISDN_IN_ODS();
        int prostredi = funkceHodnotaButtonu_Prostredi();
        CHECK_MSISDN_IN_ODS.spustCheckODS(prostredi);

    }//GEN-LAST:event_jButton5_ODS_checkActionPerformed

    private void jButton_GSM_VSE_ShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GSM_VSE_ShopActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
        int Zakaznici_pocet = (int) pocetZakazniku.getValue();
        boolean dokoncit = jCheckBox1_dokoncit.isSelected();
        /*     String ICOString = jTextField_ICO.getText();
         if (jTextField_ICO.getText().equals("")) {
         Component frame = null;
         JOptionPane.showMessageDialog(frame, "Nejdříve vyplň hodnotu IČO");
         } else {
         int ICOInt = Integer.parseInt(ICOString);
         */
        try {
            GSM_VSE_shop.proved_GSM_VSE_shop_skript(prostredi, Zakaznici_pocet, dokoncit);
        } catch (SQLException ex) {
            Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_GSM_VSE_ShopActionPerformed

    private void jButtonTCloudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTCloudActionPerformed
        try {
            int prostredi = funkceHodnotaButtonu_Prostredi();
            TCloud.proved_TCloud_skript(prostredi);
        } catch (SQLException ex) {
            Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonTCloudActionPerformed

    private void GSM_aktivace_potencialaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GSM_aktivace_potencialaActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
//        int Zakaznici_pocet = (int) pocetZakazniku.getValue();
//        boolean dokoncit = jCheckBox1_dokoncit.isSelected();
        String ICOString = jTextField_ICO.getText();
        if (jTextField_ICO.getText().equals("")) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň hodnotu IČO");
        } else {
            try {
                GSM_VSE_Potencial_ngCRM.proved_GSM_VSE_skript(prostredi, ICOString);
            } catch (SQLException ex) {
                Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_GSM_aktivace_potencialaActionPerformed

    private void GSM_LE_s_BAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GSM_LE_s_BAActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
//        int Zakaznici_pocet = (int) pocetZakazniku.getValue();
//        boolean dokoncit = jCheckBox1_dokoncit.isSelected();
        String ICOString = jTextField_ICO.getText();
        if (jTextField_ICO.getText().equals("")) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň hodnotu IČO");
        } else {
            try {
                GSM_LE_Pridruzeni_s_BA.proved_GSM_LE_pridruzeni_sBA_skript(prostredi, ICOString);
            } catch (SQLException ex) {
                Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_GSM_LE_s_BAActionPerformed

    private void GSM_LE_bez_BAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GSM_LE_bez_BAActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
//        int Zakaznici_pocet = (int) pocetZakazniku.getValue();
//        boolean dokoncit = jCheckBox1_dokoncit.isSelected();
        String ICOString = jTextField_ICO.getText();
        if (jTextField_ICO.getText().equals("")) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň hodnotu IČO");
        } else {

            try {
                GSM_LE_Pridruzeni_bez_BA.proved_GSM_LE_pridruzeni_sBA_skript(prostredi, ICOString);
            } catch (SQLException ex) {
                Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_GSM_LE_bez_BAActionPerformed

    private void DSL_reselling_VSE_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DSL_reselling_VSE_buttonActionPerformed
        int prostredi = funkceHodnotaButtonu_Prostredi();
        String ICOString = jTextField_ICO.getText();
        if (jTextField_ICO.getText().equals("")) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Nejdříve vyplň hodnotu IČO");
        } else {

            try {
                DSL_VSE_reselling.proved_xDSL_VSE_skript(ICOString, prostredi);

            } catch (InterruptedException ex) {
                Logger.getLogger(MenuGUI_jFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_DSL_reselling_VSE_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI_jFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI_jFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI_jFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI_jFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI_jFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DSLMulti_VSE_button;
    private javax.swing.JButton DSLSimple_VSE_button;
    private javax.swing.JButton DSL_reselling_VSE_button;
    private javax.swing.JButton GSM_LE_bez_BA;
    private javax.swing.JButton GSM_LE_s_BA;
    private javax.swing.JButton GSM_Postpaid_button;
    private javax.swing.JButton GSM_Postpaid_pridruzeni_button;
    private javax.swing.JButton GSM_VSE_button;
    private javax.swing.JButton GSM_VSE_nova_faktura;
    private javax.swing.JButton GSM_VSE_pridruzeni_button;
    private javax.swing.JButton GSM_aktivace_potenciala;
    private javax.swing.JButton Lessana_GSM_postpaid;
    private javax.swing.JButton MobilCZ_Postpaid_button;
    private javax.swing.JButton MobilCZ_VSE_button;
    private javax.swing.JButton Mobilcz_pridruzeni;
    private javax.swing.JButton RWE_Postpaid_button1;
    private javax.swing.JButton RWE_VSE_button1;
    private javax.swing.JButton VSE_voip;
    private javax.swing.JTextField ViceSU;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cuid_predseda;
    private javax.swing.JButton jButton4_CLF_check;
    private javax.swing.JButton jButton5_ODS_check;
    private javax.swing.JButton jButtonKonec;
    private javax.swing.JButton jButtonRWE_PridruzeniSU;
    private javax.swing.JButton jButtonTCloud;
    private javax.swing.JButton jButton_CCM_dokonceni_zadosti;
    private javax.swing.JButton jButton_GSM_VSE_Shop;
    private javax.swing.JButton jButton_Tel_linka_Postpaid_NGOSIP;
    private javax.swing.JButton jButton_Tel_linka_Postpaid_Trifid;
    private javax.swing.JButton jButton_Tel_linka_Postpaid_Trifid_Pridruzeni;
    private javax.swing.JButton jButton_Tel_linka_Postpaid_Trifid_nova_faktura;
    private javax.swing.JButton jButton_Tel_linka_VSE;
    private javax.swing.JButton jButton_Tel_linka_VSE_NGOSIP;
    private javax.swing.JButton jButton_Tel_linka_VSE_Trifid_Pridruzeni;
    private javax.swing.JButton jButton_Tel_linka_VSE_Trifid_nova_faktura;
    private javax.swing.JButton jButton_VSE_Autopark;
    private javax.swing.JCheckBox jCheckBox1_ICOzeSouboru;
    private javax.swing.JCheckBox jCheckBox1_dokoncit;
    private javax.swing.JCheckBox jCheckBox1_splatkac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1_tarif;
    private javax.swing.JRadioButton jRadioButton2_tarif;
    private javax.swing.JRadioButton jRadioButton_test1;
    private javax.swing.JRadioButton jRadioButton_test2;
    private javax.swing.JRadioButton jRadioButton_test3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3_pocetZakazniku;
    private javax.swing.JTextField jTextFieldCisloKPridruzeni;
    private javax.swing.JTextField jTextField_ICO;
    private javax.swing.ButtonGroup mojeGroupa;
    private javax.swing.JSpinner pocetZakazniku;
    private javax.swing.JButton telefonni_linka_vse_ngosip_asc;
    // End of variables declaration//GEN-END:variables
}
